language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - npm run build
  - echo 'token is:'$GITHUB_TOKEN

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master
